version: '3'

services:
  backend:
    restart: always
    container_name: 'back'
    build: ./back
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./back:/back
    ports:
      - 8080:8000

  db_hw10:
    image: postgres
    container_name: 'db_hw10'
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=maindb_hw10
      - POSTGRES_PASSWORD=maindb_hw10
      - POSTGRES_DB=maindb_hw10
    volumes:
      - ./compose/dbs/postgres-data:/var/lib/postgresql